require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

# Rails用の設定を有効化
Rails:
  Enabled: true

# ------------ For Ruby ------------ #

AsciiComments:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
  - 'Gemfile'

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 100

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/application.rb'
  AutoCorrect: true
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
  - 'Gemfile'
  - 'Rakefile'
  - 'config.ru'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 190

# ------------ For Rails ------------ #

Rails/BulkChangeTable:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: slashes

Rails/HasManyOrHasOneDependent:
  Exclude:
  - 'app/models/user.rb'

# ------------ For Rspec ------------ #

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_line_only
